// F-1 (D-35): synthetic preview fixture set for the builder's FINAL LOOK tab (U-4).
// Every figure here is GENERATED by running M-2's computeInvoice — never
// hand-written — so the tax ladder in the preview is arithmetically real, not
// typed-and-hoped-correct. Fully synthetic merchant/item data; the D-28
// whitelist this shape follows has no customer-identifying fields at all, so
// this is zero-PII by construction, not by scrubbing.
import { computeInvoice, InvoiceLineInput } from '../bills/invoice-calc';

// Fictional merchant, distinct from the seeded demo merchant (apps/api/prisma/seed.ts)
// on purpose — fixtures must not accidentally carry real-looking seed data.
// gstin[0:2] matches gstStateCode per D-25.
const FIXTURE_MERCHANT = {
  name: 'Fixture Preview Traders',
  gstin: '27AAAAA0000A1Z5',
  gstStateCode: '27',
  state: 'Maharashtra',
  address: 'Fixture Lane, Preview Nagar, 000001',
} as const;

export interface FixtureItem {
  lineNo: number;
  name: string;
  hsn: string;
  uom: string;
  quantity: number;
  unitPricePaise: string;
  itemDiscountPaise: string;
  billDiscountAllocPaise: string;
  taxRateBp: number;
  taxableValuePaise: string;
  taxPaise: string;
  cgstPaise: string;
  sgstPaise: string;
  igstPaise: string;
}

// Mirrors the D-28 whitelist shape exactly (apps/api/src/bills/bills.service.ts's
// snapshot construction is the other place this shape is built, from the real
// write path — kept as two independent constructions on purpose, since the test
// that actually guards drift is the key-set-vs-whitelist check in
// preview-fixtures.spec.ts, not shared code).
export interface FixtureSnapshot {
  merchantName: string;
  currency: string;
  amountPaise: string;
  invoiceNumber: string;
  placeOfSupply: string;
  merchantGstin: string;
  merchantState: string;
  merchantAddress: string;
  subtotalPaise: string;
  discountPaise: string;
  taxPaise: string;
  cgstPaise: string;
  sgstPaise: string;
  igstPaise: string;
  items: FixtureItem[];
}

interface FixtureItemInput {
  name: string;
  hsn: string;
  uom: string;
  quantity: number;
  unitPricePaise: bigint;
  itemDiscountPaise?: bigint;
  taxRateBp: number;
}

function buildFixture(params: {
  invoiceNumber: string;
  placeOfSupply: string;
  items: FixtureItemInput[];
  billDiscountPaise?: bigint;
}): FixtureSnapshot {
  const lines: InvoiceLineInput[] = params.items.map((item, i) => ({
    lineNo: i + 1,
    quantity: item.quantity,
    unitPricePaise: item.unitPricePaise,
    itemDiscountPaise: item.itemDiscountPaise ?? 0n,
    taxRateBp: item.taxRateBp,
  }));

  const result = computeInvoice(lines, params.billDiscountPaise ?? 0n, params.placeOfSupply, FIXTURE_MERCHANT.gstStateCode);

  const items: FixtureItem[] = result.lines.map((line, i) => ({
    lineNo: line.lineNo,
    name: params.items[i].name,
    hsn: params.items[i].hsn,
    uom: params.items[i].uom,
    quantity: params.items[i].quantity,
    unitPricePaise: lines[i].unitPricePaise.toString(),
    itemDiscountPaise: lines[i].itemDiscountPaise.toString(),
    billDiscountAllocPaise: line.billDiscountAllocPaise.toString(),
    taxRateBp: line.taxRateBp,
    taxableValuePaise: line.taxableValuePaise.toString(),
    taxPaise: line.taxPaise.toString(),
    cgstPaise: line.cgstPaise.toString(),
    sgstPaise: line.sgstPaise.toString(),
    igstPaise: line.igstPaise.toString(),
  }));

  return {
    merchantName: FIXTURE_MERCHANT.name,
    currency: 'INR',
    amountPaise: result.totalPaise.toString(),
    invoiceNumber: params.invoiceNumber,
    placeOfSupply: params.placeOfSupply,
    merchantGstin: FIXTURE_MERCHANT.gstin,
    merchantState: FIXTURE_MERCHANT.state,
    merchantAddress: FIXTURE_MERCHANT.address,
    subtotalPaise: result.subtotalPaise.toString(),
    discountPaise: result.discountPaise.toString(),
    taxPaise: result.taxPaise.toString(),
    cgstPaise: result.cgstPaise.toString(),
    sgstPaise: result.sgstPaise.toString(),
    igstPaise: result.igstPaise.toString(),
    items,
  };
}

// 40 deterministic lines cycling through valid GST slabs (0/5/12/18/28%) and
// varying quantity/price — no randomness, so this fixture is stable across runs.
function build40Lines(): FixtureItemInput[] {
  const slabsBp = [0, 500, 1200, 1800, 2800];
  return Array.from({ length: 40 }, (_, i) => ({
    name: `Preview Item ${i + 1}`,
    hsn: '1234',
    uom: 'NOS',
    quantity: (i % 5) + 1,
    unitPricePaise: BigInt(10000 + i * 137),
    taxRateBp: slabsBp[i % slabsBp.length],
  }));
}

export const PREVIEW_FIXTURES = {
  // A few lines, mixed tax slabs, intra-state — the common case.
  TYPICAL: buildFixture({
    invoiceNumber: 'FIXTURE-TYPICAL',
    placeOfSupply: FIXTURE_MERCHANT.gstStateCode,
    items: [
      { name: 'Preview Widget', hsn: '1234', uom: 'NOS', quantity: 2, unitPricePaise: 50000n, taxRateBp: 1800 },
      { name: 'Preview Gadget', hsn: '5678', uom: 'NOS', quantity: 1, unitPricePaise: 125000n, taxRateBp: 1200 },
      { name: 'Preview Accessory', hsn: '9012', uom: 'NOS', quantity: 3, unitPricePaise: 15000n, taxRateBp: 500 },
    ],
  }),

  // Exercises long tables / print pagination in the preview (V-6-style stress).
  LONG_40_LINES: buildFixture({
    invoiceNumber: 'FIXTURE-LONG-40',
    placeOfSupply: FIXTURE_MERCHANT.gstStateCode,
    items: build40Lines(),
  }),

  // placeOfSupply differs from the fixture merchant's gstStateCode — exercises
  // the IGST branch of computeInvoice (D-24) instead of CGST/SGST.
  INTER_STATE_IGST: buildFixture({
    invoiceNumber: 'FIXTURE-INTERSTATE',
    placeOfSupply: '29', // Karnataka — deliberately not '27'
    items: [
      { name: 'Preview Export Item', hsn: '4321', uom: 'NOS', quantity: 4, unitPricePaise: 75000n, taxRateBp: 1800 },
      { name: 'Preview Freight Item', hsn: '8765', uom: 'NOS', quantity: 1, unitPricePaise: 20000n, taxRateBp: 1200 },
    ],
  }),

  // Every line at 0% — exercises the all-zero tax ladder (no CGST/SGST/IGST rows
  // should render anything but zero).
  ZERO_RATED: buildFixture({
    invoiceNumber: 'FIXTURE-ZERO-RATED',
    placeOfSupply: FIXTURE_MERCHANT.gstStateCode,
    items: [
      { name: 'Preview Zero-Rated Item A', hsn: '1111', uom: 'NOS', quantity: 2, unitPricePaise: 30000n, taxRateBp: 0 },
      { name: 'Preview Zero-Rated Item B', hsn: '2222', uom: 'NOS', quantity: 1, unitPricePaise: 10000n, taxRateBp: 0 },
    ],
  }),

  // Smallest possible valid document — one line, minimal figures.
  MINIMAL: buildFixture({
    invoiceNumber: 'FIXTURE-MINIMAL',
    placeOfSupply: FIXTURE_MERCHANT.gstStateCode,
    items: [{ name: 'Preview Single Item', hsn: '0001', uom: 'NOS', quantity: 1, unitPricePaise: 100n, taxRateBp: 500 }],
  }),
} as const satisfies Record<'TYPICAL' | 'LONG_40_LINES' | 'INTER_STATE_IGST' | 'ZERO_RATED' | 'MINIMAL', FixtureSnapshot>;

export type FixtureKey = keyof typeof PREVIEW_FIXTURES;
