// W-1 verify: drives the REAL running apps/api server (and, for the login
// round-trip, the real dev-idp) to prove the two things the portal shell
// promises:
//   1. GET /portal/me is sourced from the CALLING session's MerchantContext,
//      never a shared/global value — two different sessions must see two
//      different merchant names. The seed only provisions one eligible
//      subject/merchant, so a second merchant + session is created directly
//      here (and cleaned up), never touching prisma/seed.ts.
//   2. /auth/login's returnTo makes /auth/callback redirect back to the
//      originally requested /portal path, not always to /portal root — and
//      an unsafe returnTo (off /portal) is rejected, falling back to root.
import { PrismaClient } from '@prisma/client';
import { randomBytes, createHash } from 'crypto';

const API_BASE = process.env.API_BASE_URL ?? 'http://localhost:4000';
const PUBLIC_BILL_BASE_URL = process.env.PUBLIC_BILL_BASE_URL ?? 'http://localhost:3000';
const prisma = new PrismaClient();

interface CookieJar {
  [name: string]: string;
}
function mergeCookies(jar: CookieJar, res: Response) {
  for (const raw of res.headers.getSetCookie()) {
    const [pair] = raw.split(';');
    const eq = pair.indexOf('=');
    jar[pair.slice(0, eq)] = pair.slice(eq + 1);
  }
}
function cookieHeader(jar: CookieJar): string {
  return Object.entries(jar).map(([k, v]) => `${k}=${v}`).join('; ');
}

function fail(message: string): never {
  console.error(`\nFAIL — ${message}\n`);
  process.exit(1);
}

// Same devInteractions-driving approach as verify-a2-login-session.ts.
async function driveRealLogin(loginAsSubject: string, returnTo?: string): Promise<{ jar: CookieJar; finalStatus: number; redirectedTo?: string }> {
  const jar: CookieJar = {};
  const loginUrl = returnTo ? `${API_BASE}/auth/login?returnTo=${encodeURIComponent(returnTo)}` : `${API_BASE}/auth/login`;
  let next = loginUrl;
  let hops = 0;

  while (hops++ < 15) {
    const isCallbackUrl = next.startsWith(`${API_BASE}/auth/callback`);
    const res = await fetch(next, { redirect: 'manual', headers: { cookie: cookieHeader(jar) } });
    mergeCookies(jar, res);

    if (res.status >= 300 && res.status < 400) {
      if (isCallbackUrl) {
        return { jar, finalStatus: 200, redirectedTo: res.headers.get('location') ?? undefined };
      }
      const location = res.headers.get('location')!;
      next = new URL(location, next).href;
      continue;
    }

    if (res.status === 200 && next.includes('/interaction/')) {
      const uid = next.split('/interaction/')[1].split(/[/?]/)[0];
      const html = await res.text();
      const isConsent = html.includes('name="prompt" value="consent"');
      const idpOrigin = new URL(next).origin;
      const body = isConsent
        ? new URLSearchParams({ prompt: 'consent' })
        : new URLSearchParams({ prompt: 'login', login: loginAsSubject, password: 'irrelevant' });

      const submitRes = await fetch(`${idpOrigin}/interaction/${uid}`, {
        method: 'POST',
        redirect: 'manual',
        headers: { 'content-type': 'application/x-www-form-urlencoded', cookie: cookieHeader(jar) },
        body: body.toString(),
      });
      mergeCookies(jar, submitRes);
      next = new URL(submitRes.headers.get('location')!, idpOrigin).href;
      continue;
    }

    return { jar, finalStatus: res.status };
  }
  throw new Error('too many redirects');
}

// Matches SessionService's own hashToken exactly (same conversion, so the
// Prisma-generated Bytes type lines up) — not imported since it's private there.
function hashToken(token: string): Uint8Array<ArrayBuffer> {
  const digest = createHash('sha256').update(token).digest();
  const out = new Uint8Array(new ArrayBuffer(digest.length));
  out.set(digest);
  return out;
}

async function main() {
  console.log('\n=== W-1 verify: portal shell (/portal/me sourcing, returnTo round-trip) ===\n');

  // ---- 1. /portal/me with no cookie at all ----
  console.log('1. GET /portal/me with no session cookie...');
  const anonRes = await fetch(`${API_BASE}/portal/me`);
  console.log(`   HTTP ${anonRes.status}`);
  if (anonRes.status !== 401) fail(`expected 401 with no session cookie, got ${anonRes.status}`);
  console.log('   PASS\n');

  // ---- 2. real login as the seeded subject, /portal/me matches that merchant ----
  console.log('2. Real login as the seeded subject, then GET /portal/me...');
  const { jar: jarA } = await driveRealLogin('seed-user-merchant-admin');
  const sessionA = jarA['session'];
  if (!sessionA) fail('no session cookie after seeded-subject login');

  const seededSession = await prisma.merchantSession.findFirst({
    where: { tokenHash: hashToken(sessionA) },
    include: { user: { include: { merchant: true } } },
  });
  if (!seededSession?.user.merchant) fail('could not resolve the seeded session back to a merchant in the DB');
  const seededMerchantName = seededSession.user.merchant.name;

  const meResA = await fetch(`${API_BASE}/portal/me`, { headers: { cookie: `session=${sessionA}` } });
  if (meResA.status !== 200) fail(`expected 200 from /portal/me, got ${meResA.status}`);
  const meA = (await meResA.json()) as { merchantName: string; role: string };
  console.log(`   /portal/me -> merchantName="${meA.merchantName}", role=${meA.role}`);
  if (meA.merchantName !== seededMerchantName) fail(`expected merchantName "${seededMerchantName}", got "${meA.merchantName}"`);
  console.log('   PASS — matches the seeded merchant\'s own DB row\n');

  // ---- 3. a SECOND merchant + session (created here, not in seed.ts) sees ITS OWN name ----
  console.log('3. A second merchant/session (scratch, cleaned up after) must see a DIFFERENT name...');
  const merchantB = await prisma.merchant.create({
    data: {
      jiopayMid: `w1-verify-mid-${Date.now()}`,
      name: 'W-1 Verify Second Merchant',
      secretKeyEnc: Buffer.from('unused'),
    },
  });
  const userB = await prisma.user.create({
    data: {
      merchantId: merchantB.id,
      type: 'EXTERNAL',
      role: 'MERCHANT_ADMIN',
      email: `w1-verify-${Date.now()}@example.invalid`,
      subject: `w1-verify-subject-${Date.now()}`,
    },
  });
  const rawTokenB = randomBytes(32).toString('base64url');
  await prisma.merchantSession.create({
    data: { userId: userB.id, tokenHash: hashToken(rawTokenB), expiresAt: new Date(Date.now() + 60_000) },
  });

  try {
    const meResB = await fetch(`${API_BASE}/portal/me`, { headers: { cookie: `session=${rawTokenB}` } });
    if (meResB.status !== 200) fail(`expected 200 from /portal/me for second merchant, got ${meResB.status}`);
    const meB = (await meResB.json()) as { merchantName: string; role: string };
    console.log(`   /portal/me -> merchantName="${meB.merchantName}"`);
    if (meB.merchantName !== merchantB.name) fail(`expected "${merchantB.name}", got "${meB.merchantName}"`);
    if (meB.merchantName === meA.merchantName) fail('second session saw the SAME merchant name as the first — not session-scoped');
    console.log('   PASS — different session, different merchant name, no cross-talk\n');
  } finally {
    await prisma.merchantSession.deleteMany({ where: { userId: userB.id } });
    await prisma.user.delete({ where: { id: userB.id } });
    await prisma.merchant.delete({ where: { id: merchantB.id } });
  }

  // ---- 4. returnTo: a valid /portal path round-trips through login+callback ----
  console.log('4. /auth/login?returnTo=/portal/bills/abc123 round-trips to that exact path...');
  const { redirectedTo: returnToLocation } = await driveRealLogin('seed-user-merchant-admin', '/portal/bills/abc123');
  console.log(`   redirected to: ${returnToLocation}`);
  const expectedReturnTo = `${PUBLIC_BILL_BASE_URL}/portal/bills/abc123`;
  if (returnToLocation !== expectedReturnTo) fail(`expected redirect to "${expectedReturnTo}", got "${returnToLocation}"`);
  console.log('   PASS\n');

  // ---- 5. an unsafe returnTo (off /portal) is rejected, falls back to /portal root ----
  console.log('5. /auth/login?returnTo=https://evil.example/portal falls back to /portal root...');
  const { redirectedTo: unsafeLocation } = await driveRealLogin('seed-user-merchant-admin', 'https://evil.example/portal');
  console.log(`   redirected to: ${unsafeLocation}`);
  const expectedFallback = `${PUBLIC_BILL_BASE_URL}/portal`;
  if (unsafeLocation !== expectedFallback) fail(`expected fallback redirect to "${expectedFallback}", got "${unsafeLocation}"`);
  console.log('   PASS — open-redirect attempt rejected\n');

  console.log('=== all W-1 checks passed ===\n');
  await prisma.$disconnect();
}

main().catch(async (err) => {
  console.error('verify-w1-portal-shell crashed:', err);
  await prisma.$disconnect();
  process.exit(1);
});
